/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pinkas.onmuhasebe.gui;
import com.pinkas.onmuhasebe.dal.tblmusteridao;
import com.pinkas.onmuhasebe.models.tblmusteri;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vektorel
 */
public class frmSatis_MusteriListesi extends javax.swing.JFrame {
    tblmusteridao  db = new tblmusteridao();
    /**
     * Creates new form frmSatis_MusteriListesi
     */
    public frmSatis_MusteriListesi() {
        initComponents();
        tablodoldur(db.listele(new tblmusteri()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablomusteri = new javax.swing.JTable();
        txtad = new javax.swing.JTextField();
        txtsoyad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablomusteri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Müşteri Adı", "Müşteri Soyadı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablomusteri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablomusteriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablomusteri);
        if (tablomusteri.getColumnModel().getColumnCount() > 0) {
            tablomusteri.getColumnModel().getColumn(0).setResizable(false);
            tablomusteri.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablomusteri.getColumnModel().getColumn(1).setPreferredWidth(150);
            tablomusteri.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 360, 460));

        txtad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtadKeyReleased(evt);
            }
        });
        getContentPane().add(txtad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 28, 150, -1));

        txtsoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoyadActionPerformed(evt);
            }
        });
        txtsoyad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsoyadKeyReleased(evt);
            }
        });
        getContentPane().add(txtsoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 28, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoyadActionPerformed
       
    }//GEN-LAST:event_txtsoyadActionPerformed

    private void tablomusteriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablomusteriMouseClicked
       frmSatis.durum=1;
       int secilenindex = tablomusteri.getSelectedRow();
       long id = Long.parseLong(tablomusteri.getValueAt(secilenindex, 0).toString());
       String ad = tablomusteri.getValueAt(secilenindex, 1).toString();
       String soyad = tablomusteri.getValueAt(secilenindex, 2).toString();
       
       frmSatis.mst.setId(id);
       frmSatis.mst.setAd(ad);
       frmSatis.mst.setSoyad(soyad);
       this.setVisible(false);
    }//GEN-LAST:event_tablomusteriMouseClicked

    private void txtadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadKeyPressed
       
        
        
    }//GEN-LAST:event_txtadKeyPressed

    private void txtadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadKeyReleased
        tblmusteri tmp = new tblmusteri();
        if(txtsoyad.getText().isEmpty()){
         tmp.setAd(txtad.getText());
            tablodoldur(db.ara(tmp));
        }
        else{
        tmp.setAd(txtad.getText());
        tmp.setSoyad(txtsoyad.getText());
            tablodoldur(db.ara(tmp));
        }
    }//GEN-LAST:event_txtadKeyReleased

    private void txtsoyadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsoyadKeyReleased
          tblmusteri tmp = new tblmusteri();
        if(txtad.getText().isEmpty()){
         tmp.setSoyad(txtsoyad.getText());
            tablodoldur(db.ara(tmp));
        }
        else{
        tmp.setAd(txtad.getText());
        tmp.setSoyad(txtsoyad.getText());
            tablodoldur(db.ara(tmp));
        }
    }//GEN-LAST:event_txtsoyadKeyReleased

    
    public void tablodoldur(List<tblmusteri> list){
        
        int i=0;
        tablotemizle();
        for(tblmusteri item: list){
         tablosatirekle();
         tablomusteri.setValueAt(item.getId(), i,0);
         tablomusteri.setValueAt(item.getAd(), i,1);
         tablomusteri.setValueAt(item.getSoyad(), i,2);
      
         i++;
        }
        
    }
    
    
     public void tablotemizle(){    
        DefaultTableModel dtm = 
                (DefaultTableModel)this.tablomusteri.getModel();
        dtm.getDataVector().removeAllElements();
        this.tablomusteri.repaint();
    }
    
    public void tablosatirekle(){
         DefaultTableModel dtm = 
                (DefaultTableModel)this.tablomusteri.getModel();
         dtm.setRowCount(dtm.getRowCount()+1);
         this.tablomusteri.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSatis_MusteriListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSatis_MusteriListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSatis_MusteriListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSatis_MusteriListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSatis_MusteriListesi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablomusteri;
    private javax.swing.JTextField txtad;
    private javax.swing.JTextField txtsoyad;
    // End of variables declaration//GEN-END:variables
}
