/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pinkas.onmuhasebe.gui;
import com.pinkas.onmuhasebe.dal.tblmarkadao;
import com.pinkas.onmuhasebe.dal.tblmodeldao;
import com.pinkas.onmuhasebe.dal.tblsatisdao;
import com.pinkas.onmuhasebe.dal.tblsatisdetaydao;
import com.pinkas.onmuhasebe.models.tblmarka;
import com.pinkas.onmuhasebe.models.tblmodel;
import com.pinkas.onmuhasebe.models.tblmusteri;
import com.pinkas.onmuhasebe.models.tblsatis;
import com.pinkas.onmuhasebe.models.tblsatisdetay;
import com.pinkas.onmuhasebe.util.StaticValues;
import java.time.Instant;
import java.util.Date;

import javax.swing.JOptionPane;

/**
 *
 * @author vektorel
 */
public class frmSatis extends javax.swing.JFrame {

    public static int durum = 0;
    
    public static tblmusteri mst = new tblmusteri();
    
    tblsatisdao dbsatis = new tblsatisdao();
    
    tblsatisdetaydao dbsatisdetay = new tblsatisdetaydao();
    
    tblmodeldao dbmodel = new tblmodeldao();
    
    tblmarkadao dbmarka = new tblmarkadao();
    
    /**
     * Creates new form frmSatis
     */
    public frmSatis() {
        initComponents();
        for(tblmarka item : dbmarka.listele(new tblmarka())){
        combomarka.addItem(item.getAd());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsoyad = new javax.swing.JTextField();
        btnmusteriara = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        combomarka = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtbirimfiyat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtadet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttoplamfiyat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtodenen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtkalan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttarih = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        comboboxkasaturu = new javax.swing.JComboBox<>();
        btnsatisyap = new javax.swing.JButton();
        combomodel = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        combourun = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 70, -1));

        jLabel2.setText("Ad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtad.setEditable(false);
        txtad.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(txtad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 160, -1));

        jLabel3.setText("Soyad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtsoyad.setEditable(false);
        txtsoyad.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(txtsoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 160, -1));

        btnmusteriara.setText("ARA");
        btnmusteriara.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnmusteriara.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmusteriara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmusteriaraActionPerformed(evt);
            }
        });
        getContentPane().add(btnmusteriara, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 70, 20));

        jLabel4.setText("Marka");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        combomarka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));
        combomarka.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combomarkaİtemStateChanged(evt);
            }
        });
        getContentPane().add(combomarka, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 320, -1));

        jLabel5.setText("Birim Fiyat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        txtbirimfiyat.setEditable(false);
        txtbirimfiyat.setBackground(new java.awt.Color(153, 153, 153));
        txtbirimfiyat.setText("250");
        getContentPane().add(txtbirimfiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 120, -1));

        jLabel6.setText("Adet");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        txtadet.setText("1");
        txtadet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtadetKeyReleased(evt);
            }
        });
        getContentPane().add(txtadet, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 120, -1));

        jLabel7.setText("Toplam Fiyat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        txttoplamfiyat.setEditable(false);
        txttoplamfiyat.setBackground(new java.awt.Color(153, 153, 153));
        txttoplamfiyat.setText("0");
        getContentPane().add(txttoplamfiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 120, -1));

        jLabel8.setText("Ödenen");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        txtodenen.setText("0");
        txtodenen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtodenenKeyReleased(evt);
            }
        });
        getContentPane().add(txtodenen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 120, -1));

        jLabel9.setText("Kalan");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        txtkalan.setEditable(false);
        txtkalan.setBackground(new java.awt.Color(153, 153, 153));
        txtkalan.setText("0");
        getContentPane().add(txtkalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 120, -1));

        jLabel10.setText("Tarih");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        try {
            txttarih.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txttarih, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 120, -1));

        jLabel11.setText("Kasa Türü");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        comboboxkasaturu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz...", "Peşin", "K.Kartı" }));
        getContentPane().add(comboboxkasaturu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 250, -1));

        btnsatisyap.setText("SATIŞ YAP");
        btnsatisyap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnsatisyap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsatisyapActionPerformed(evt);
            }
        });
        getContentPane().add(btnsatisyap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 400, 40));

        combomodel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));
        getContentPane().add(combomodel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 320, -1));

        jLabel12.setText("Model");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        combourun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", " " }));
        getContentPane().add(combourun, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 320, -1));

        jLabel13.setText("Ürün");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmusteriaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmusteriaraActionPerformed
       frmSatis_MusteriListesi frm = new frmSatis_MusteriListesi();
       frm.setVisible(true);
    }//GEN-LAST:event_btnmusteriaraActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(durum==1){
            //JOptionPane.showMessageDialog(this, "Müşteri Seçildi");
            txtid.setText(mst.getId()+"");
            txtad.setText(mst.getAd());
            txtsoyad.setText(mst.getSoyad());
            
            durum=0;
        }
    }//GEN-LAST:event_formWindowActivated

    private void txtadetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadetKeyReleased
        try {
            if(!txtadet.getText().isEmpty()){
            int adet = Integer.parseInt(txtadet.getText());
            double birimfiyat = Double.parseDouble(txtbirimfiyat.getText());
            double toplam = adet * birimfiyat;
            txttoplamfiyat.setText(toplam+"");
            }
            else{
            txttoplamfiyat.setText("0");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Lütfen Geçerli bir değer giriniz");
            txtadet.setText("");
        }
    }//GEN-LAST:event_txtadetKeyReleased

    private void txtodenenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtodenenKeyReleased
        try {
            if(!txtodenen.getText().isEmpty()){
            double toplamfiyat = Double.parseDouble(txttoplamfiyat.getText());
            double odenen = Double.parseDouble(txtodenen.getText());
            double kalan = toplamfiyat - odenen;
            txtkalan.setText(kalan+"");                   
            }
            else{
                txtkalan.setText("0");
        }
                   
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this,"Lütfen Geçerli bir değer giriniz");
             txtodenen.setText("");
        }
    }//GEN-LAST:event_txtodenenKeyReleased

    private void btnsatisyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsatisyapActionPerformed
       tblsatis st = new tblsatis();
       st.setIslemtarihi(new Date());
       st.setKalan(Double.parseDouble(txtkalan.getText()));
       //st.setKasaid(ABORT);
       st.setMusteriid(mst.getId());
       st.setOdenen(Double.parseDouble(txtodenen.getText()));
       st.setPersonelid(StaticValues.personel.getId());
       st.setSatistarihi(Date.from(Instant.parse(txttarih.getText())));
       st.setToplamfiyat(Double.parseDouble(txttoplamfiyat.getText()));
       
       dbsatis.kaydet(st);
       
        tblsatisdetay std = new tblsatisdetay();
        std.setBirimadedi(Integer.parseInt(txtadet.getText()));
        std.setBirimfiyat(Double.parseDouble(txtbirimfiyat.getText()));
        //std.setSatisid(ABORT); ????
        std.setToplamfiyat(Double.parseDouble(txttoplamfiyat.getText()));
        //std.setUrunid();
        
        dbsatisdetay.kaydet(std);
        
    }//GEN-LAST:event_btnsatisyapActionPerformed

    private void combomarkaİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combomarkaİtemStateChanged
        combomodel.removeAllItems();
        combomodel.addItem("Seçiniz....");
        for(tblmodel item : dbmodel.listeModel(1)){
        combomodel.addItem(item.getAd());
        }
    }//GEN-LAST:event_combomarkaİtemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSatis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmusteriara;
    private javax.swing.JButton btnsatisyap;
    private javax.swing.JComboBox<String> comboboxkasaturu;
    private javax.swing.JComboBox<String> combomarka;
    private javax.swing.JComboBox<String> combomodel;
    private javax.swing.JComboBox<String> combourun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtad;
    private javax.swing.JTextField txtadet;
    private javax.swing.JTextField txtbirimfiyat;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkalan;
    private javax.swing.JTextField txtodenen;
    private javax.swing.JTextField txtsoyad;
    private javax.swing.JFormattedTextField txttarih;
    private javax.swing.JTextField txttoplamfiyat;
    // End of variables declaration//GEN-END:variables
}
